spring:
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:user}
      password: ${SPRING_SECURITY_USER_PASSWORD:password}
app:
  auth:
    jwt:
      access-expiration: ${APP_AUTH_JWT_ACCESS_EXPIRATION:P3D}
      refresh-expiration: ${APP_AUTH_JWT_REFRESH_EXPIRATION:P15D}
      secret-key: ${APP_AUTH_JWT_SECRET_KEY:asldfkjaasnasdklfjalekjfslakcnvlaskejlfisajdkfalseifn}
